---
title: ""
---

<br><br><br>

Use these old exams (some with solutions) with *extreme caution*. The current version of this course deviates substantially from the way I taught this course until now. The exams from 2012 are particularly unrepresentative.

* [Summer 2016, Test 2 D100](./exams/20160726-BUEC333-D100-Test2-sols.pdf)
* [Summer 2016, Test 2 D200](./exams/20160727-BUEC333-D200-Test2-sols.pdf)

* [Summer 2016, Test1 D100](./exams/20160613-BUEC333-D100-Test1_withsol.pdf)
* [Summer 2016, Test1 D200](./exams/20160613-BUEC333-D200-Test1_Solutions.pdf)

* [Summer 2015, Test 1 ](./exams/20150603-BUEC333-Test1-Sol.pdf)
* [Summer 2015, Test 2](./exams/20150603-BUEC333-Test2-withsols.pdf)
* [Summer 2015, Test 3](./exams/20150805-BUEC333-Test3-sols.pdf)
* [Summer 2014, midterm](./exams/20140619_midterm333_answers.pdf)
* [Summer 2014, final](./exams/20140806-FInal-answers.pdf)
* [Summer 2013, midterm](./exams/20130613_midterm333_sols.pdf)
* [Summer 2013, final](./exams/20130808_final333.pdf), and [answers](./exams/20130808_Answers_Final_333.pdf)
* [Fall 2012, midterm](./exams/20121015_midterm333_A_sols.pdf)
* [Fall 2012, final](./exams/201212-buec333-fall-2012-final.pdf)
* [Spring 2012, midterm](./exams/20120224_midterm_BUEC333_spring2012.pdf), [solutions](./exams/20120224_midterm_BUEC333_spring2012_sol.pdf)
* [Spring 2012, final](./exams/201204-buec333-spring-2012-d200-final.pdf), [answers](./exams/201204-buec333-spring-2012-d200-final-solutions.pdf)

