---
title: ""
---

<br>
<br>
This is the course website for BUEC 333, Summer 2016. 
<br>
<br>

* Instructor: Chris Muris
* Office: WMC 3639
* Office hours: Thursdays, 10:00-12:00.
* No email: talk to me before or after class, in the breaks, or during my office hours.
* [Syllabus](./admin/Syllabus-BUEC333-Summer2016.pdf)
* [Regrade request form](./admin/regradingForm.pdf)
* Open labs: In WMC 2506, from week 4, with
    - D100: Tim on Wednesdays 14:30-17:20
    - D200: Meiyu on Fridays 13:30-16:20
   
<br>
<br>

#### Schedule

| Week of  |         | Topic                          | Event     |
|----------|---------|--------------------------------|-----------|
| May 9    | Week 1  | Probability Theory             |           |
| May 16   | Week 2  | Sampling                       |           |
| May 23   | Week 3  | Statistics                     |           |
| May 30   | Week 4  | Linear regression: Mechanics   |           |
| June 6   | Week 5  | Linear regression: Statistics  |           |
| June 13  | Test 1  |                                | Test 1    |
| June 20  | Week 6  | Multiple linear regression     | Hand-in 1 |
| June 27  | Week 7  | Nonlinear regression |           |
| July 4   | Week 8  | Instrumental variables      |           |
| July 11  | Week 9  | Validity          |           |
| July 18  | Week 10 | Panel data
| July 25  | Test 2  |                                | Test 2    |
| August 1 | Week 11 | TBD | Hand-in 2 |

<br>

#### Weekly material {.tabset .tabset-pills}

Readings and exercises are from Stock and Watson, "Introduction to Econometrics", Third Edition (Updated).

<br>

##### Week 1

* Topic: Introduction and Probability theory.
* Self-study: 1, 2.1, 2.2 (skip "Other measures...")
* In-class: 2.3 (skip: "Means and sums of random variables")
* In-class exercises: 2.2, 2.6
* Tutorial exercises: No tutorials, see "Week 1" under Week 2's tutorials.
* Lab: No labs, but see next week's if you want a head start.
* More material:
    - [intro slides](./slides/week1-intro.pdf)

##### Week 2

* Topic: Sampling
* Self-study: 2.5
* In-class: 2.3 ("Means and sums of random variables"), 2.4 ("Normal distribution"), 2.6, 3.1
* In-class exercises: 2.10 (a)+(c), 2.22, 2.17
* Tutorial exercises: 
    - Related to Week 1: 2.1, 2.9, 2.20
    - Related to week 2: 2.3, 2.7, 2.10(b)+(d), 2.18, 2.23
* Lab: Follow steps 1-5 (or 6!) at [swirl](http://swirlstats.com/students.html) and go through the course "R Programming"
* More material:
    - [CLT demonstration](http://blog.vctr.me/posts/central-limit-theorem.html)
    - Expectation of $Y=aX+b$ for a continnuous RV $X$: [pdf](./notes/expectation-of-a-linear-transformation-of-a-continuous-random-variable.pdf)

##### Week 3

* Topic: Statistics
* Self-study: 3.2 (skip "One-sided alternatives")
* In-class: 3.1, 3.3, 3.4
* In-class exercises: 3.5, 3.10, 3.13
* Tutorial exercises: 3.1, 3.3, 3.4, 3.8, 3.9, 3.16
* Lab: Finish the "R Programming" course in Swirl. 
* More material:
    - In-class R [code](./code/week3-STAR.R), and [data](./code/testscores_california_1999.csv)

##### Week 4

* Topic: Linear regression: Mechanics
* Self-study: 4.1
* In-class: 4.2, 4.3
* In-class exercises: 4.4, 4.5, 4.7
* Tutorial exercises: 4.1, 4.2, 4.3, 4.9
* Lab: You will learn 
    - basic data operations (load, arrange/organize, and subset data)
    - computing summary statistics of variables: mean, variance, ...
* More material:
    - Here is a great (but slightly outdated) video on RMarkdown: [video](https://youtu.be/-apyD5f9nwg)
    - In-class R [code](./code/week4-STAR-reg.R), and a bit of [Markdown](./code/week4-RMarkdown.Rmd)


##### Week 5

* Topic: Linear regression: Statistics
* Self-study: 4.5
* In-class: 4.4, 5.1, 5.2, 5.3
* In-class exercises: 5.1, 5.3
* Tutorial exercises: 4.10, 5.2, 5.4, 5.5
* Lab: You will learn about visualization, and about regression. 
    - plots and interpretation
    - predict outcomes based on observed data
    - regressions: run, display and interpret results, confidence intervals and testing
    - [script](./labfiles/BasicExercises2.R) and [data](./labfiles/testdata.csv)


##### Week 6

* Topic: Multiple linear regression
* Self-study: Sections 6.1 and 6.2
* In-class: Sections 6.3, 6.4, 6.5, 6.6, 6.7
* In-class exercises: 6.5 and 6.6
* Tutorial exercises: 6.1, 6.2, 6.3, 6.4, 6.9
* Lab: Final week for HI1.
    - [script](./labfiles/week5/script.R)
    - [Markdown](./labfiles/week5/Test.Rmd)

##### Week 7

* Topic: Nonlinear regression
* Self-study: 7.1, 7.5, 7.6
* In-class: 8.1, 8.2, 8.3 (until "Interactions between two continuous variables")
* In-class exercises: 7.11, 8.7
* Tutorial exercises: 7.1, 7.2, 7.3, 7.5, 8.1, 8.2 
* Lab: Focus on questions 6.1 and 7.1 in your hand-in assignment.
* More material
    - Hockey player salary [script](./code/week7-1-hockey.R) and [hockey data](./code/NHL1998-99.csv) + [yield data](./code/yield.txt)
    - Quadratic regression [script](./code/week7-2-nonlinear-yield.R)
    - Log wage regression [script](./code/week7-3-logs.R), [data1](./code/WAGE1.DTA), [data2](./code/WAGE2.DTA)

##### Week 8

* Topic: Instrumental variables
* Read (after class): 12.4, 12.5
* In-class: 12.1, 12.2
* In-class exercises: Wooldridge 15.2 and 15.7 
* Tutorial exercises: 12.2, 12.9
* Lab: Focus on exercise E12.1
* More material:
    - Inspiration for education/wages example: [Youtube](https://www.youtube.com/watch?v=FQ3d2syNfYI)
    - Another good [video](https://www.youtube.com/watch?v=NLgB2WGGKUw) on IV estimation

##### Week 9

* Topic: Internal and external validity
* Self-study: 9.1, 9.2, 9.3, 9.4
* In-class: Exercises only (week 9 + recap weeks 6-8)
* In-class exercises: 
    - Wk 9: 9.6
    - Wk 6: 6.6
    - Wk 7: 8.4, 8.5
    - Old exams: Summer 2015, Test 3, Q4+6
* Tutorial exercises: 9.1, 9.2, 9.7, 9.11
* Lab: Focus on putting your answers so far in acceptable format

##### Week 10

* Topic: Panel data
* Self-study: Section 10.1
* In-class: Sections 10.2, 10.3, 10.4, 10.5
* In-class exercises: Section 10.6
* Tutorial exercises: 10.3, ...
* Lab: Focus on exercise 10.1

##### Week 11

* Topic: Time series, or other (by request)
* Self-study: TBD
* In-class: TBD
* In-class exercises: TBD
* Tutorial exercises: TBD
* Lab: TBD

