---
title: "Hand-in assignments"
---

<br>

In this course, you will learn how to use a statistical computing environment called "R" to implement the tools you learn in this course. 

We use R, with RStudio, because it is free, and because it works on all major operating systems (OSX, Linux, Windows). 

I will demonstrate using R during the lectures, there are dedicated computer labs, and there are two hand-in assignments. This page provides additional details. 

#### Useful resources

* R can de downloaded from its [official website](http://www.r-project.org)
* A free, cross-platform, user-friendly frontend for R is RStudio. It can be downloaded [here](http://www.rstudio.com)
* You will be learning R from within R, using [swirl](http://swirlstats.com/students.html)
* An excellent way to learn R is by studying "Introduction", "Basics", and "Linear regression" in 
    "Applied econometrics with R" by Christian Kleiber and Achim Zeileis. It is available online through the SFU library through [this link](http://link.springer.com/book/10.1007/978-0-387-77318-6/page/1)

#### Hand-in assignments

##### Formatting instructions

Your hand-in assignment is a written assignment. 

In addition to the R code that is at the heart of your answers, you are expect to give answers to the questions in full sentences, in English. 

*You are responsible for delivering a readable html document.*

Every subquestion starts with a sentence or two explaining what you are going to do. Then, there will be some code, and R output (print only what you need to answer the question). Finally, a sentence or two to interpret the findings, and answer the question. Whenever you use code from a source (internet, lab, fellow student), give proper reference.

An example of what we expect, using E4.1, follows. These instructions are in addition to the instructions in the hand-in assignment itself.

* Rmd: [.Rmd](./assignments/buec333-handin-formatting.Rmd)
* html: [.html](./assignments/buec333-handin-formatting.html)
* Annotated pdf: [.pdf](./assignments/buec333-handin-formatting.pdf) with annotations
    
More importantly, here is a list of things *not* to do, some with an html file that demonstrates what went wrong. We will subtract points for violations. When in doubt, consult your lab TA.

1. Do not print entire data frames, [html](./assignments/buec333-handin-formatting-1.html). The output just looks ridiculous, and the TA has to scroll through hundreds of pages to read your answer.
2. Do not use "###"" for text, only for headers [html](./assignments/buec333-handin-formatting-2.html). In MS Word, you would not format your written text as "Heading 1" either. Regular text has no "#" in front of it. Use "#" only for headers for (sub-)questions. See the example above.
3. Do not put you actual answer inside a code block as a comment. Try grading 10 pages of [this](./assignments/buec333-handin-formatting-3.html)
4. Do not use a separate files for each question. You will receive 0 points. Hand in 1 (one) Rmd file, and 1 (one) html file.
5. Do not hand in your assignment without checking your html file first. Your html file is the file that the TA uses to grade your assignment. If it is not readable, you will receive 0 points. Generating a readable html file is your responsibility.
6. Print to screen only the variable you need for your answer. Do not print every single variable. If the question asks for a confidence interval, do not report know what the standard error and then 1.96 times the standard error is.
    - Do not show a summary object with >10 components, and assume that we will find that one number that you were asked to report.
    - Do not print data exploration ('head(df)', 'tail(df)', 'str(df)', etc.) to the screen, unless asked for by the question.
7. Do not use tools you do not understand. Example: 'plot(lm(...))' produces a whole bunch of graphs that don't answer the question)

* [Hand-in assignment 1](./assignments/Handin-1.pdf)
    - Solutions [rmd](./assignments/AnswerKey1.Rmd)
    - Solutions [html](./assignments/AnswerKey1.html)


* [Hand-in assignment 2](./assignments/Handin-2.pdf)
